app.py
from flask import Flask, Blueprint, render_template, request, redirect
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from utils import db,lm
from controllers.usuario import bp_usuarios
from controllers.livros_create import bp_livros_create
from models.usuario import Usuario
from models.livros_create import livros_create

# Inicializando o Flask
app = Flask(__name__)

# Configuração do banco de dados
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///app.db'
app.config['SECRET_KEY'] = 'PIZZA'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

# Inicializando o banco de dados
db.init_app(app)
lm.init_app(app)
migrate = Migrate(app, db)

# Registrando Blueprints
app.register_blueprint(bp_usuarios, url_prefix='/user')
app.register_blueprint(bp_livros_create, url_prefix='/livros_create')

# Rotas principais
@app.route('/')
def capa():
    return render_template('capa.html')

@app.route('/Sobre')
def sobre():
    return render_template('Sobre.html')

@app.route('/Volta')
def Volta():
    return render_template('volta.html')

@app.route('/biblioteca')
def biblioteca():
    livros= livros_create.query.all()
    return render_template('biblioteca.html',livros=livros)

@app.route('/Perfil')
def perfil():
    return render_template('Perfil.html')

@app.route('/suporte_create', methods=['GET', 'POST'])
def suporte_create():
    return render_template('suporte_create.html')


@app.route('/favoritos')
def favoritos():
    return render_template('favoritos.html')
# Rota para a página inicial


@app.route('/historico')
def historico():
    return render_template('historico.html')

@app.route('/configuracoes')
def configuracoes():
    return render_template('configuracoes.html')

@app.route('/inicio')
def inicio():
    return render_template('capa.html')

@app.errorhandler(401)
def acesso_negado(e):
    return render_template('acesso_negado.html'), 404

if __name__ == '__main__':
    app.run(debug=True)

controllers/livros_create.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from utils import db,lm
from models.livros_create import livros_create
from flask import Blueprint
from flask_login import login_required

bp_livros_create = Blueprint("livros_create", __name__, template_folder='templates')


@login_required
@bp_livros_create.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'GET':
        return render_template('livros_create.html')  # Ajuste no nome do template

    if request.method == 'POST':
        titulo = request.form.get('titulo')
        print(titulo)
        ano = request.form.get('ano')
        curso = request.form.get('curso')
        link = request.form.get('link')
        materia = request.form.get('materia')


        novo_livro =livros_create(titulo, ano, curso, link, materia)
        db.session.add(novo_livro)
        db.session.commit()

        return redirect(url_for('biblioteca')) 
    
    
@login_required
@bp_livros_create.route('/<id>/update', methods=['GET', 'POST'])
def update(id):
    if request.method == 'GET':
        livro = livros_create.query.filter_by(id=id).first()
        return render_template('livros_update.html', livro=livro)  # Ajuste no nome do template

    if request.method == 'POST':
        titulo = request.form.get('titulo')
        print(titulo)
        ano = request.form.get('ano')
        curso = request.form.get('curso')
        link = request.form.get('link')
        materia = request.form.get('materia')

        livro = livros_create.query.filter_by(id=id).first()
        livro.titulo = titulo
        livro.ano = ano
        livro.curso = curso
        livro.link = link
        livro.materia = materia
        db.session.commit()

        return redirect(url_for('biblioteca')) 
    
@bp_livros_create.route('/<id>/delete')
def delete(id):
    livro = livros_create.query.filter_by(id=id).first()
    db.session.delete(livro)
    db.session.commit()
    return redirect(url_for('biblioteca'))


@bp_livros_create.route('/recovery')
def recovery():
    if request.method == 'GET':
        livros= livros_create.query.all()
        print(livros)
        return render_template("biblioteca.html",livros = livros)

controllers/usuario.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from utils import db,lm
from models.usuario import Usuario
from flask_login import login_user, logout_user
from flask import Blueprint
from models.livros_create import livros_create
from werkzeug.security import generate_password_hash, check_password_hash

bp_usuarios = Blueprint("usuarios", __name__, template_folder='templates')

@bp_usuarios.route('/create', methods=['GET', 'POST'])
def create():
    if request.method=='GET':
        return render_template('Cadastro.html')
    if request.method=='POST':
        nome = request.form.get('nome')
        email = request.form.get('email')
        senha = request.form.get('senha')
        senha_criptografada = generate_password_hash(senha)
        admin=request.form.get('admin')
        print(len(nome))
        if len(nome) < 3:
            flash('nome precisa de mais de 3 letras para o nome')
            return redirect(url_for('usuarios.create'))
        if len(senha) < 3 :
            flash('senha precisa de mais de 3 caractere para a senha')
            return redirect(url_for('usuarios.create'))
        if Usuario.query.filter_by(email=email).first():
            flash('Email já cadastrado!')
            return redirect(url_for('usuarios.create'))
        
          
        usuario = Usuario(nome, email, senha_criptografada, admin)
        db.session.add(usuario)
        db.session.commit()

        login_user(usuario)

        return redirect(url_for('biblioteca'))

@bp_usuarios.route('/delete/<int:id>', methods=['GET', 'POST'])
def delete(id):
    if id==0:
        flash('É preciso definir um usuário para ser excluído')
        return redirect(url_for('.recovery'))

    if request.method == 'GET':
        usuario = Usuario.query.get(id)
        return render_template('usuarios_delete.html', usuario = usuario)

    if request.method == 'POST':
        usuario = Usuario.query.get(id)
        db.session.delete(usuario)
        db.session.commit()
        flash('Usuário excluído com sucesso')
        return redirect(url_for('.recovery'))

@lm.user_loader
def load_user(id):
    usuario = Usuario.query.filter_by(id=id).first()
    #usuario = Usuario.query.get(id)
    return usuario

@bp_usuarios.route('/autenticar', methods=['GET','POST'])
def autenticar():
    if request.method == 'GET':
            return render_template('usuario_create.html')
    
    if request.method == 'POST':
        email = request.form.get('email')
        senha = request.form.get('senha')
        usuario = Usuario.query.filter_by(email = email).first()
        if usuario is None:
            return redirect(url_for('usuarios.autenticar'))
        if (senha is not None and check_password_hash(usuario.senha, senha)):
            login_user(usuario)
            return redirect(url_for('biblioteca'))
        else:
            flash('Dados incorretos')
            return redirect(url_for('usuarios.autenticar'))
      
      
@bp_usuarios.route('/update/<int:id>', methods=['GET', 'POST'])
def update(id):
    if request.method=='GET':
        return render_template('usuarios_create.html')
    if request.method=='POST':
        usuario = Usuario.query.get(id)
        return render_template('usuarios_update.html', usuario=usuario)

    if (request.method=='POST'):
        usuario = Usuario.query.get(id)
        usuario.nome = request.form.get('nome')
        usuario.email = request.form.get('email')
        usuario.senha = request.form.get('senha')
            
    if (request.form.get('senha') and request.form.get('senha') == request.form.get('csenha')):
        usuario.senha = request.form.get('senha')
    else:
        flash('Senhas não conferem')
        return redirect(url_for('.update', id=id)) 

        db.session.add(usuario) 
        db.session.commit()
        flash('Dados atualizados com sucesso!')
        return redirect(url_for('.recovery', id=id))
    
@bp_usuarios.route('/logout')
def logout():
    logout_user()
    return render_template('capa.html')

templates/alteracao de dados.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>alteracao de dados</title>
    <link rel="stylesheet" href="suporte_create.css">
</head>
<body>
<div class="container">
    <div class="form-area">
        <h1>Contato Suporte</h1>
        <form>
            <label for="nome">Nome completo</label>
            <input type="text" id="nome" placeholder="Seu nome" required>

            <label for="email">E-mail</label>
            <input type="email" id="email" placeholder="Seu e-mail" required>

            <label for="mensagem">Mensagem/label>
            <input type="mensagem" id="mensagem" placeholder="mensagem" required>

            <button type="submit">Salvar</button>
            <button type="submit">Cancelar</button>
       


           
        </form>
    </div>
</div>
</body>
</html>

templates/biblioteca.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Biblioteca Digital</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/biblioteca.css') }}">
</head>
<body>
  <nav class="top-nav">
    <a href="{{url_for('inicio')}}" class="nav-link">Inicio</a>
    <a href="{{ url_for('perfil') }}" class="nav-link">Perfil</a>
    <a href="{{ url_for('usuarios.logout') }}" class="nav-link">Sair</a>
    <a href="/templates/capa.html"></a>
  </nav>

  <div class="search-container">
    <input type="text" class="search-input" placeholder="Pesquisar livros, autores ou assuntos...">
    <button class="search-button">Pesquisar</button>
    {%  if current_user.admin == 1  %}
      <button class="admbutton">
        <a href="{{url_for('livros_create.create')}}">Criar livros</a>
      </button>
    {% endif %}
  </div>

  <div class="main-container">
    <div class="sidebar">
      <h3 class="sidebar-title">Áreas Técnicas</h3>
      <div class="sidebar-section">
        <h4>Os Mais Lidos da Semana</h4>
        {% for livro in livros %} 
        {% if livro.curso == 'informatica' %}
          <a href="" class="sidebar-link">{{livro.ano}}° Ano - {{livro.materia}}</a>
        
        {% endif %}
      {% endfor %}

      </div>
      <div class="sidebar-section">
        <h4>Seleção de Melhores Livros</h4>
        {% for livro in livros %} 
        {% if livro.curso == 'comercio' %}
          <a href="" class="sidebar-link">{{livro.ano}}° Ano - {{livro.materia}}</a>
        
        {% endif %}
      {% endfor %}

      </div>
      <div class="sidebar-section">
        <h4>Os Mais Procurados</h4>
        {% for livro in livros %} 
        {% if livro.curso == 'eletronica' %}
          <a href="" class="sidebar-link">{{livro.ano}}° Ano - {{livro.materia}}</a>
        
        {% endif %}
      {% endfor %}

      </div>
    </div>

    <div class="content">
      <div class="section-header">
        <h2>Informática</h2>
      </div>
      {% for livro in livros %} 
        {% if livro.curso == 'informatica' %}
          <div class="course-card">
            <div class="course-code">{{ livro.ano }}° ano</div>
            <div class="course-code">{{livro.titulo}}</div>
            <div class="course-title">
              <a href="{{ livro.link }}" target="_blank">{{ livro.materia }}</a><br>
              <a href="{{ livro.link }}" target="_blank">link</a>
              {%  if current_user.admin == 1  %}
              <br>
              <button><a href="{{url_for('livros_create.update', id=livro.id)}}">Editar</a></button>
              <button><a href="{{url_for('livros_create.delete', id=livro.id)}}">Excluir</a></button>
              {% endif %}
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>

    <div class="content">
      <div class="section-header">
        <h2>Comércio</h2>
      </div>
      {% for livro in livros %} 
        {% if livro.curso == 'comercio' %}
          <div class="course-card">
            <div class="course-code">{{ livro.ano }}° ano</div>
            <div class="course-title">
              <a href="{{ livro.link }}" target="_blank">{{ livro.materia }}</a><br>
              <a href="{{ livro.link }}" target="_blank">link</a>
              {%  if current_user.admin == 1  %}
              <br>
              <button><a href="{{url_for('livros_create.update', id=livro.id)}}">Editar</a></button>
              <button><a href="{{url_for('livros_create.delete', id=livro.id)}}">Excluir</a></button>
              {% endif %}
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>

    <div class="content">
      <div class="section-header">
        <h2>Eletrônica</h2>
      </div>
      {% for livro in livros %} 
        {% if livro.curso == 'eletronica' %}
          <div class="course-card">
            <div class="course-code">{{ livro.ano }}° ano</div>
            <div class="course-title">
              <a href="{{ livro.link }}" target="_blank">{{ livro.materia }}</a><br>
              <a href="{{ livro.link }}" target="_blank">link</a>
              {%  if current_user.admin == 1  %}
              <br>
              <button><a href="{{url_for('livros_create.update', id=livro.id)}}">Editar</a></button>
              <button><a href="{{url_for('livros_create.delete', id=livro.id)}}">Excluir</a></button>
              {% endif %}

            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
</body>
</html>

templates/cadastro.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Cadastro</title>
    <link rel="stylesheet" href="cadastro.css">
</head>
<body>
<div class="container">
    <div class="form-area">
        <h1>Crie sua Conta</h1>
        <form>
            <label for="nome">Nome completo</label>
            <input type="text" id="nome" placeholder="Seu nome" required>

            <label for="email">E-mail</label>
            <input type="email" id="email" placeholder="Seu e-mail" required>

            <label for="senha">Senha</label>
            <input type="password" id="senha" placeholder="Sua senha" required>

            <label for="confirmar">Confirmar senha</label>
            <input type="password" id="confirmar" placeholder="Confirme sua senha" required>

            <label for="confirmar">Sexo</label>
            <input type="sexo" id="sexo" placeholder="sexo" required>
            
            <label for="confirmar">Data de Nascimento</label>
            <input type="data de nascimento" id="data de nascimento" placeholder="data de nascimento" required>

            <label for="adm">É administrador?</label>
            <select id="adm" required>
                <option value="" disabled selected>Selecione...</option>
                <option value="sim">Sim</option>
                <option value="nao">Não</option>
            </select>

            <button type="submit">Criar conta</button>

            <p class="link-login">
                Já tem uma conta? <a href="{{ url_for('usuarios.autenticar') }}">Faça login</a>
            </p>
        </form>
    </div>

    <div class="imagem">
        <img src="https://i.ibb.co/6y4mV4P/book.png" alt="Ícone livro">
    </div>
</div>
</body>
</html>

templates/capa.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Library Connect</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/capa.css') }}">
</head>
<body>
    <header class="topo">
        <div class="logo">
            <img src="https://i.ibb.co/G4sQWdkg/image.png">
        </div>

        <nav class="menu">
            <a href="#">Conheça a biblioteca</a>
            <a href="#">Destaques</a>
            <a href="#">Contatos</a>
        </nav>

        <div class="botoes">
            <button>Cadastro</button>
            <button>Login</button>
        </div>
    </header>
    <section class="banner">
        <div class="banner-texto">
            <h1>Bem-vindo à sua<br> Biblioteca Virtual</h1>
            <p>O conhecimento do mundo ao seu alcance.<br>A qualquer hora, em qualquer lugar.</p>
            <button class="btn-explorar">Explorar</button>
        </div>
    </section>

    <section class="destaques">
        <h2 class="destaque-titulo">Destaques do acervo</h2>

        <div class="livros">
            <img src="https://i.ibb.co/m5cFXCRj/image.png">
            <img src="https://i.ibb.co/CKsKZYbx/image.png">
            <img src="https://i.ibb.co/cSHtBHPx/image.png">
            <img src="https://i.ibb.co/5W8WCS46/image.png">
        </div>
    </section>
    <section class="criar-conta">
        <div class="caixa-conta">

            <div class="caixa-img">
                <img src="https://i.ibb.co/QsmW6sm/image.png">
            </div>

            <div class="caixa-texto">
                <h2>Crie uma conta</h2>
                <p>Baixe livros e leia de qualquer lugar</p>
                <button class="btn-criar">Criar</button>
            </div>

        </div>
    </section>
    <footer class="rodape">
        <div class="rodape-conteudo">

            <div class="coluna-esquerda">
                <h3>📘 Library Connect</h3>
                <p class="siga-title">Siga-nos</p>

                <div class="social-icons">
                    <img src="https://i.ibb.co/YkZ9N0s/facebook.png">
                    <img src="https://i.ibb.co/18JsNpH/instagram.png">
                </div>
            </div>

            <div class="coluna-direita">
                <h4>Navegação</h4>
                <ul>
                    <li><a href="#">Início</a></li>
                    <li><a href="#">Recurso</a></li>
                    <li><a href="#">Termos de Uso</a></li>
                    <li><a href="#">Política de Privacidade</a></li>
                </ul>
            </div>

        </div>

        <div class="rodape-direitos">
            © LibraryConnect — todos os direitos reservados
        </div>
    </footer>

</body>
</html>

templates/dados.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>alteracao de dados pessoais</title>
</head>
<body>

<div class="container">
    <div class="form-area">
        <form>
            <label for="nome">Nome completo</label>
            <input type="text" id="nome" placeholder="Seu nome" required>

            <label for="email">E-mail</label>
            <input type="email" id="email" placeholder="Seu e-mail" required>

            <label for="senha">Senha</label>
            <input type="password" id="senha" placeholder="Sua senha" required>
           
            <button type="submit">Salvar</button>
            <button type="submit">Cancelar</button>
        </form>
    </div>
</div>
</body>
</html>

templates/livros_create.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <title>Biblioteca Virtual - Criar livro</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/cadastro.css') }}">
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="nav-wrapper">
                <div class="logo-container">
                    <!-- Você pode adicionar o logo aqui -->
                </div>
            </div>
        </div>
    </header>

    <main class="container">
        <div class="cadastro-container">
            <form class="cadastro-form" action="{{ url_for('livros_create.create') }}" method="POST">
                <h2 style="text-align: center; color: #191970; margin-bottom: 30px;">Criar livro</h2>

                <div class="form-group">
                    <label for="titulo">titulo</label>
                    <input type="text" id="titulo" name="titulo" required>
                </div>

                <div class="form-group">
                    <label for="ano">ano</label>
                    <select name="ano">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                      </select><br>
                </div>

                <div class="form-group">
                    <label for="curso">curso</label>
                    <select name="curso">
                        <option value="comercio">Comercio</option>
                        <option value="eletronica">Eletronica</option>
                        <option value="informatica">Informatica</option>
                      </select><br>
                </div>

                <div class="form-group">
                    <label for="materia">materia</label>
                    <input type="text" id="materia" name="materia" required>
                </div> 
                <div class="form-group">
                    <label for="link">link</label>
                    <input type="text" id="link" name="link" required>
                </div>
                <button type="submit" class="cadastro-btn">Criar</button>
            </form>
        </div>
    </main>
</body>
</html>

templates/livros_update.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <title>Biblioteca Virtual - Editar livro</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/cadastro.css') }}">
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="nav-wrapper">
                <div class="logo-container">
                    <!-- Você pode adicionar o logo aqui -->
                </div>
            </div>
        </div>
    </header>

    <main class="container">
        <div class="cadastro-container">
            <form class="cadastro-form" action="{{ url_for('livros_create.update', id=livro.id) }}" method="POST">
                <h2 style="text-align: center; color: #191970; margin-bottom: 30px;">Editar livro</h2>

                <div class="form-group">
                    <label for="titulo">titulo</label>
                    <input type="text" id="titulo" name="titulo" required value="{{livro.titulo}}">
                </div>

                <div class="form-group">
                    <label for="ano">ano</label>
                    <select name="ano">
                        <option {% if livro.ano=='1' %} selected {% endif %} value="1">1</option>
                        <option {% if livro.ano=='2' %} selected {% endif %} value="2">2</option>
                        <option {% if livro.ano=='3' %} selected {% endif %} value="3">3</option>
                        <option {% if livro.ano=='4' %} selected {% endif %} value="4">4</option>
                      </select><br>
                </div>

                <div class="form-group">
                    <label for="curso">curso</label>
                    <select name="curso">
                        <option {% if livro.curso=='comercio' %} selected {% endif %} value="comercio">Comercio</option>
                        <option {% if livro.curso=='eletronica' %} selected {% endif %} value="eletronica">Eletronica</option>
                        <option {% if livro.curso=='informatica' %} selected {% endif %} value="informatica">Informatica</option>
                      </select><br>
                </div>

                <div class="form-group">
                    <label for="materia">materia</label>
                    <input type="text" id="materia" name="materia" value="{{livro.materia}}" required>
                </div> 
                <div class="form-group">
                    <label for="link">link</label>
                    <input type="text" id="link" name="link" value="{{livro.link}}" required>
                </div>
                <button type="submit" class="cadastro-btn">Editar</button>
            </form>
        </div>
    </main>
</body>
</html>

templates/perfil.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>perfil</title>
</head>
<body>
    
    <div class="informacoes">
        <a href="historico" class="nav-link">Historico de Leitura</a>
        <a href="favoritos" class="nav-link">Livros Favoritos</a>
        <a href="suporte_create" class="nav-link">Suporte</a>
        <a href="alteracao de dados" class="nav-link">altera seus dados</a>
    </div>

</body>
</html>

templates/suporte_create.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Suporte</title>
    <link rel="stylesheet" href="suporte_create.css">
</head>
<body>
<div class="container">
    <div class="form-area">
        <h1>Contato Suporte</h1>
            <label for="nome">Nome completo</label>
            <input type="text" id="nome" placeholder="Seu nome" required>

            <label for="email">E-mail</label>
            <input type="email" id="email" placeholder="Seu e-mail" required>

            <label for="mensagem">Mensagem/label>
            <input type="mensagem" id="mensagem" placeholder="mensagem" required>

            <button type="submit">Enviar mensagem</button>

           
        </form>
    </div>
</div>
</body>
</html>

templates/usuario_create.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <title>Biblioteca Virtual - Login</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
</head>
<body>
        <header class="header">
        <div class="container">
            <div class="nav-wrapper">
            <div class="logo-container">
            </div>
            </div>
        </div>
    </header>
    <main class="container">
        <div class="login-container">
            <h2 style="text-align: center; color: #003366; margin-bottom: 30px; font-family: Poltawski Nowy; font-size: 30px;">Faça seu Login </h2>
            <form id="loginForm">
                <div class="form-group">
                    <label for="email">E-mail</label>
                    <input type="email" id="email" name="email" required>
                    <div class="error-message" id="emailError">Por favor, insira um e-mail válido.</div>
                </div>
                <div class="form-group">
                    <label for="senha">Senha</label>
                    <input type="password" id="senha" name="senha" required>
                    <div class="error-message" id="passwordError">A senha deve ter pelo menos 6 caracteres.</div>
                </div>
                <button type="submit" class="login-btn">Entrar</button>
                <div class="forgot-password">
                    <a href="recuperar-senha">Esqueceu sua senha?</a>
                </div>
                <div class="register-link">
                </div>
            </form>
        </div>
    </main>
</body>
</html>